name: "Setup Node.js & Dependencies"
description: "Checkout code, setup Node.js, enable Corepack, and install dependencies"

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: "20"
        cache: "yarn"

    - name: Enable Corepack
      shell: bash
      run: corepack enable

    - name: Install dependencies
      shell: bash
      run: yarn install --immutable
