yarnPath: .yarn/releases/yarn-4.12.0.cjs
nodeLinker: pnp
pnpMode: "loose"

packageExtensions:
  "vite@*":
    dependencies:
      rollup: "*"
  "@storybook/nextjs-vite@*":
    peerDependencies:
      vite: "*"
  "@storybook/react-vite@*":
    peerDependencies:
      vite: "*"
