yarnPath: .yarn/releases/yarn-4.12.0.cjs
nodeLinker: pnp
pnpMode: "loose"

packageExtensions:
  "vite@*":
    dependencies:
      rollup: "*"
  "@storybook/nextjs-vite@*":
    dependencies:
      vite: "*"
      rollup: "*"
  "@storybook/react-vite@*":
    dependencies:
      vite: "*"
      rollup: "*"
  "@storybook/core-server@*":
    dependencies:
      "@types/node": "*"
  "vite-tsconfig-paths@*":
    dependencies:
      globrex: "*"
