nodeLinker: pnp

packageExtensions:
  "@storybook/nextjs-vite@*":
    dependencies:
      rollup: "*"
      vite: "*"
  "@storybook/react-vite@*":
    dependencies:
      rollup: "*"
      vite: "*"
  vite-tsconfig-paths@*:
    dependencies:
      globrex: "*"
  vite@*:
    dependencies:
      globrex: "*"
      rollup: "*"

pnpMode: loose

yarnPath: .yarn/releases/yarn-4.12.0.cjs
